# Generated by Django 4.0.2 on 2022-06-14 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='business_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=50)),
                ('latitude', models.TextField(max_length=150)),
                ('longitude', models.TextField(max_length=150)),
                ('business_name', models.CharField(max_length=50)),
                ('business_desc', models.CharField(max_length=200)),
                ('business_address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('subcategory', models.CharField(max_length=200)),
                ('irich', models.TextField(max_length=200)),
                ('business_code', models.CharField(max_length=50)),
                ('Account_details', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('IFSC_code', models.CharField(max_length=50)),
                ('business_contact', models.CharField(max_length=50)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='deals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sId', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': '0. Payment Method',
            },
        ),
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('targeted_amount', models.CharField(max_length=500)),
                ('referral_member', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=200)),
                ('session_id', models.CharField(max_length=200)),
                ('Customer', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('earning', models.CharField(max_length=50)),
                ('irich_bonus', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.business_details')),
                ('irich_walletamount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.wallet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referral_code', models.TextField(max_length=150)),
                ('phone', models.BigIntegerField()),
                ('postcode', models.TextField(max_length=150)),
                ('referral', models.CharField(max_length=150)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.business_details')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.roles')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='business_details',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.category'),
        ),
        migrations.AddField(
            model_name='business_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
