# Generated by Django 4.0.2 on 2022-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='irich_bonus',
            field=models.FloatField(default=0),
        ),
    ]
