# Generated by Django 4.0.2 on 2022-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_payments_irich_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_details',
            name='irich',
            field=models.FloatField(default=1),
        ),
    ]
