# Generated by Django 4.0.2 on 2022-06-16 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_alter_business_details_irich'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-06-16 10:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PaymentProcessComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_process_complete',
            },
        ),
    ]
