# Generated by Django 4.0.2 on 2022-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_payments_created_at_payments_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='starting_irich_bonus',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
