# Generated by Django 4.0.2 on 2022-07-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_wallet_starting_irich_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
